//! Stat rules from `packages/data/tables/*.toml` and `packages/data/classes/*.toml`
//! (Story E1.2; the files are generated by `packages/data/scripts/gen_tables.py`).
//!
//! Loading is all-or-nothing: every file is parsed, every decimal is parsed exactly (no
//! binary floating point anywhere on this path), every literal is checked against its
//! stored scaled integer, coverage and cross-file references are checked, and the result
//! goes through [`StatRules::new`]. Any problem aborts startup with **every** error listed.
//! [`ResolvedRules::config_hash`] is a SHA-256 over a canonical JSON encoding of the parsed
//! files, so comments and formatting do not change it and any value change does.

use super::exact_decimal::parse_decimal;

use std::collections::BTreeMap;
use std::fmt;
use std::path::Path;

use serde::{Deserialize, Serialize};
use sha2::{Digest, Sha256};

use crate::application::zone_bootstrap::ResolvedRules;
use crate::domain::zone::{
    Archetype, BonusTable, ClassTemplate, FormulaConstants, Quadratic, Scaled, StatBonusTables,
    StatRules, StatRulesParts, WeaponBlock, BONUS_TABLE_LEN, Q,
};
use crate::domain::{BaseStats, Race};

macro_rules! data_file {
    ($path:literal) => {
        ($path, include_str!(concat!("../../../../packages/data/", $path)))
    };
}

/// The rule files compiled into the binary, so the server starts without a data directory.
pub const EMBEDDED: [(&str, &str); 14] = [
    data_file!("tables/stat_bonus.toml"),
    data_file!("tables/formulas.toml"),
    data_file!("tables/experience.toml"),
    data_file!("tables/penalties.toml"),
    data_file!("tables/starter_weapon.toml"),
    data_file!("classes/dark_fighter.toml"),
    data_file!("classes/dark_mystic.toml"),
    data_file!("classes/dwarven_fighter.toml"),
    data_file!("classes/elven_fighter.toml"),
    data_file!("classes/elven_mystic.toml"),
    data_file!("classes/human_fighter.toml"),
    data_file!("classes/human_mystic.toml"),
    data_file!("classes/orc_fighter.toml"),
    data_file!("classes/orc_mystic.toml"),
];

const TABLES: [&str; 5] = [
    "tables/stat_bonus.toml",
    "tables/formulas.toml",
    "tables/experience.toml",
    "tables/penalties.toml",
    "tables/starter_weapon.toml",
];

/// Rule file contents keyed by path relative to `packages/data` (`tables/…`, `classes/…`).
#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub struct RulesSource(pub BTreeMap<String, String>);

impl RulesSource {
    /// The compiled-in files.
    #[must_use]
    pub fn embedded() -> Self {
        Self(
            EMBEDDED
                .iter()
                .map(|(p, s)| ((*p).to_owned(), (*s).to_owned()))
                .collect(),
        )
    }

    /// Reads the five tables and every `classes/*.toml` under `dir` (a `packages/data`).
    pub fn from_dir(dir: &Path) -> anyhow::Result<Self> {
        use anyhow::Context as _;
        let mut files = BTreeMap::new();
        for rel in TABLES {
            let path = dir.join(rel);
            let src = std::fs::read_to_string(&path)
                .with_context(|| format!("read {}", path.display()))?;
            files.insert(rel.to_owned(), src);
        }
        let classes = dir.join("classes");
        for entry in
            std::fs::read_dir(&classes).with_context(|| format!("read {}", classes.display()))?
        {
            let path = entry?.path();
            if path.extension().is_some_and(|e| e == "toml") {
                let name = path
                    .file_name()
                    .map(|n| n.to_string_lossy().into_owned())
                    .unwrap_or_default();
                let src = std::fs::read_to_string(&path)
                    .with_context(|| format!("read {}", path.display()))?;
                files.insert(format!("classes/{name}"), src);
            }
        }
        Ok(Self(files))
    }
}

/// Every problem found while loading; startup prints them all.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct RulesError(pub Vec<String>);

impl fmt::Display for RulesError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        writeln!(f, "stat rules rejected ({} errors):", self.0.len())?;
        for e in &self.0 {
            writeln!(f, "  - {e}")?;
        }
        Ok(())
    }
}

impl std::error::Error for RulesError {}

// ---------------------------------------------------------------------------
// Exact decimals
// ---------------------------------------------------------------------------

/// Collects errors while converting, so one bad value does not hide the next.
#[derive(Default)]
struct Errors(Vec<String>);

impl Errors {
    fn push(&mut self, msg: String) {
        self.0.push(msg);
    }

    /// Parses `literal` and checks it equals the generator's `stored` scaled integer.
    fn decimal(&mut self, ctx: &str, literal: &str, stored: Option<i64>) -> Scaled {
        match parse_decimal(literal) {
            Ok(v) => {
                if let Some(q) = stored {
                    if q != v.raw() {
                        self.push(format!(
                            "{ctx}: literal {literal} is {} at Q, stored {q}",
                            v.raw()
                        ));
                    }
                }
                v
            },
            Err(e) => {
                self.push(format!("{ctx}: {e}"));
                Scaled::ZERO
            },
        }
    }

    fn require(&mut self, ok: bool, msg: impl FnOnce() -> String) {
        if !ok {
            self.push(msg());
        }
    }
}

// ---------------------------------------------------------------------------
// File shapes (serde). Decimals are strings: a TOML float is a type error, never an f64.
// ---------------------------------------------------------------------------

#[derive(Debug, Deserialize, Serialize)]
#[serde(deny_unknown_fields)]
struct SourceRef {
    repository: String,
    revision: String,
    file: String,
    #[serde(default)]
    symbol: Option<String>,
}

#[derive(Debug, Deserialize, Serialize)]
#[serde(deny_unknown_fields)]
struct StatBonusFile {
    source: SourceRef,
    q: i64,
    min_index: u32,
    max_index: u32,
    str: BonusRows,
    dex: BonusRows,
    con: BonusRows,
    int: BonusRows,
    wit: BonusRows,
    men: BonusRows,
}

#[derive(Debug, Deserialize, Serialize)]
#[serde(deny_unknown_fields)]
struct BonusRows {
    expression: String,
    bonus: Vec<String>,
    bonus_q: Vec<i64>,
}

#[derive(Debug, Deserialize, Serialize)]
#[serde(deny_unknown_fields)]
struct GameSourceRef {
    repository: String,
    revision: String,
    config: String,
}

/// Provenance every `[formulas.<id>]` carries.
#[derive(Debug, Deserialize, Serialize)]
#[serde(deny_unknown_fields)]
struct Plain {
    file: String,
    symbol: String,
    literal: Vec<String>,
}

macro_rules! formula {
    ($name:ident { $($field:ident : $ty:ty),* $(,)? }) => {
        #[derive(Debug, Deserialize, Serialize)]
        #[serde(deny_unknown_fields)]
        struct $name {
            file: String,
            symbol: String,
            literal: Vec<String>,
            $($field: $ty,)*
        }
    };
}

formula!(LevelModF {
    offset: u32,
    divisor: u32
});
formula!(AccuracyF {
    dex_sqrt_multiplier: u32
});
formula!(EvasionF {
    dex_sqrt_multiplier: u32,
    cap: u32
});
formula!(HitF {
    base: u32,
    per_point: u32,
    scale: u32,
    min_permille: u32,
    max_permille: u32,
    roll_range: u32
});
formula!(CritF {
    scale: u32,
    cap_permille: u32,
    roll_range: u32
});
formula!(DamageF {
    coefficient: u32,
    crit_multiplier: u32
});
formula!(RandomF {
    fist_base: u32,
    divisor: u32
});
formula!(SpeedF { cap: u32 });
formula!(IntervalF {
    numerator_ms: u32,
    impact_divisor: u32
});
formula!(HateF {
    numerator: u32,
    level_offset: u32,
    cap: u64
});
formula!(XpCapF { max_level: u32 });
formula!(RespawnF {
    restore_hp: String,
    restore_hp_q: i64,
    restore_mp: String,
    restore_mp_q: i64,
    spawn_protection_seconds: u32,
});

/// The formula ids the domain evaluator implements; a missing or unknown id is an error.
#[derive(Debug, Deserialize, Serialize)]
#[serde(deny_unknown_fields)]
struct FormulaSet {
    level_mod: LevelModF,
    p_atk: Plain,
    p_def: Plain,
    max_hp: Plain,
    max_mp: Plain,
    accuracy: AccuracyF,
    evasion: EvasionF,
    hit_chance: HitF,
    crit_rate: CritF,
    phys_damage: DamageF,
    random_damage: RandomF,
    attack_speed: SpeedF,
    attack_interval: IntervalF,
    damage_hate: HateF,
    xp_cap: XpCapF,
    town_respawn: RespawnF,
}

#[derive(Debug, Deserialize, Serialize)]
#[serde(deny_unknown_fields)]
struct LevelAdditions {
    accuracy: Vec<String>,
    accuracy_q: Vec<i64>,
    evasion: Vec<String>,
    evasion_q: Vec<i64>,
}

#[derive(Debug, Deserialize, Serialize)]
#[serde(deny_unknown_fields)]
struct FormulasFile {
    source: GameSourceRef,
    q: i64,
    max_level: u32,
    formulas: FormulaSet,
    level_additions: LevelAdditions,
}

#[derive(Debug, Deserialize, Serialize)]
#[serde(deny_unknown_fields)]
struct XpRow {
    level: u32,
    xp: u64,
}

#[derive(Debug, Deserialize, Serialize)]
#[serde(deny_unknown_fields)]
struct ExperienceFile {
    source: SourceRef,
    max_level: u32,
    sentinel_level: u32,
    to_level: Vec<XpRow>,
}

#[derive(Debug, Deserialize, Serialize)]
#[serde(deny_unknown_fields)]
struct LossRow {
    level: u32,
    percent: String,
    fraction_q: i64,
}

#[derive(Debug, Deserialize, Serialize)]
#[serde(deny_unknown_fields)]
struct PenaltiesFile {
    source: SourceRef,
    max_level: u32,
    death_xp_loss: Vec<LossRow>,
}

#[derive(Debug, Deserialize, Serialize)]
#[serde(deny_unknown_fields)]
struct WeaponFile {
    source: SourceRef,
    id: String,
    item_id: u32,
    name: String,
    weapon_type: String,
    p_atk: String,
    p_atk_q: i64,
    crit_rate: u32,
    p_atk_spd: u32,
    random_damage: u32,
    attack_range: u32,
    accuracy: String,
    accuracy_q: i64,
}

#[derive(Debug, Deserialize, Serialize)]
#[serde(deny_unknown_fields)]
#[allow(clippy::struct_field_names)]
struct BaseStatsFile {
    str: u32,
    dex: u32,
    con: u32,
    int: u32,
    wit: u32,
    men: u32,
}

#[derive(Debug, Deserialize, Serialize)]
#[serde(deny_unknown_fields)]
struct CombatFile {
    p_atk: String,
    p_atk_q: i64,
    crit_rate: u32,
    p_atk_spd: u32,
    attack_range: u32,
    run_speed: u32,
    walk_speed: u32,
}

#[derive(Debug, Deserialize, Serialize)]
#[serde(deny_unknown_fields)]
struct PDefSlots {
    chest: u32,
    legs: u32,
    head: u32,
    feet: u32,
    gloves: u32,
    underwear: u32,
    cloak: u32,
}

#[derive(Debug, Deserialize, Serialize)]
#[serde(deny_unknown_fields)]
struct CurveFile {
    base: String,
    base_q: i64,
    per_level: String,
    per_level_q: i64,
    accel: String,
    accel_q: i64,
    levels: Vec<String>,
    levels_q: Vec<i64>,
}

#[derive(Debug, Deserialize, Serialize)]
#[serde(deny_unknown_fields)]
struct ClassFile {
    source: SourceRef,
    id: String,
    class_id: u32,
    name: String,
    race: String,
    archetype: String,
    base_stats: BaseStatsFile,
    combat: CombatFile,
    p_def_slots: PDefSlots,
    hp: CurveFile,
    mp: CurveFile,
}

/// The canonical form hashed into the config hash: parsed values only, in a fixed order.
#[derive(Serialize)]
struct Canonical<'a> {
    schema: &'static str,
    stat_bonus: &'a StatBonusFile,
    formulas: &'a FormulasFile,
    experience: &'a ExperienceFile,
    penalties: &'a PenaltiesFile,
    starter_weapon: &'a WeaponFile,
    classes: BTreeMap<&'a str, &'a ClassFile>,
}

struct Parsed {
    stat_bonus: StatBonusFile,
    formulas: FormulasFile,
    experience: ExperienceFile,
    penalties: PenaltiesFile,
    weapon: WeaponFile,
    classes: Vec<(String, ClassFile)>,
}

fn parse_one<T: for<'de> Deserialize<'de>>(
    src: &RulesSource,
    rel: &str,
    errs: &mut Errors,
) -> Option<T> {
    let Some(text) = src.0.get(rel) else {
        errs.push(format!("{rel}: missing"));
        return None;
    };
    match toml::from_str(text) {
        Ok(v) => Some(v),
        Err(e) => {
            errs.push(format!("{rel}: {}", e.to_string().trim_end()));
            None
        },
    }
}

fn parse_all(src: &RulesSource, errs: &mut Errors) -> Option<Parsed> {
    let stat_bonus = parse_one(src, "tables/stat_bonus.toml", errs);
    let formulas = parse_one(src, "tables/formulas.toml", errs);
    let experience = parse_one(src, "tables/experience.toml", errs);
    let penalties = parse_one(src, "tables/penalties.toml", errs);
    let weapon = parse_one(src, "tables/starter_weapon.toml", errs);
    let mut classes = Vec::new();
    for rel in src.0.keys().filter(|k| k.starts_with("classes/")) {
        if let Some(c) = parse_one::<ClassFile>(src, rel, errs) {
            classes.push((rel.clone(), c));
        }
    }
    for rel in src.0.keys() {
        let known = TABLES.contains(&rel.as_str())
            || (rel.starts_with("classes/")
                && Path::new(rel).extension().is_some_and(|e| e == "toml"));
        errs.require(known, || format!("{rel}: not a rule file"));
    }
    Some(Parsed {
        stat_bonus: stat_bonus?,
        formulas: formulas?,
        experience: experience?,
        penalties: penalties?,
        weapon: weapon?,
        classes,
    })
}

/// Loads, validates and hashes the rules. `Err` lists every problem found.
pub fn load_rules(src: &RulesSource) -> Result<ResolvedRules, RulesError> {
    let mut errs = Errors::default();
    let parsed = parse_all(src, &mut errs);
    let Some(p) = parsed.filter(|_| errs.0.is_empty()) else {
        return Err(RulesError(errs.0));
    };
    let parts = to_parts(&p, &mut errs);
    if !errs.0.is_empty() {
        return Err(RulesError(errs.0));
    }
    let rules =
        StatRules::new(parts).map_err(|v| RulesError(v.into_iter().map(|r| r.0).collect()))?;
    let canonical = Canonical {
        schema: "nightfall-stat-rules/1",
        stat_bonus: &p.stat_bonus,
        formulas: &p.formulas,
        experience: &p.experience,
        penalties: &p.penalties,
        starter_weapon: &p.weapon,
        classes: p.classes.iter().map(|(_, c)| (c.id.as_str(), c)).collect(),
    };
    let bytes = serde_json::to_vec(&canonical)
        .map_err(|e| RulesError(vec![format!("canonical encoding: {e}")]))?;
    Ok(ResolvedRules {
        rules: std::sync::Arc::new(rules),
        config_hash: format!("sha256:{}", hex(&Sha256::digest(&bytes))),
    })
}

/// Reads `dir` (a `packages/data`) and loads it; I/O errors and rule errors both abort.
pub fn load_rules_dir(dir: &Path) -> anyhow::Result<ResolvedRules> {
    Ok(load_rules(&RulesSource::from_dir(dir)?)?)
}

fn to_parts(p: &Parsed, e: &mut Errors) -> StatRulesParts {
    let max_level = p.formulas.max_level;
    check_provenance(p, e);
    e.require(p.experience.max_level == max_level, || {
        format!(
            "experience max_level {} != formulas max_level {max_level}",
            p.experience.max_level
        )
    });
    e.require(p.penalties.max_level == max_level, || {
        format!(
            "penalties max_level {} != formulas max_level {max_level}",
            p.penalties.max_level
        )
    });
    e.require(p.formulas.formulas.xp_cap.max_level == max_level, || {
        "formulas.xp_cap.max_level != max_level".to_owned()
    });
    e.require(p.experience.sentinel_level == max_level.saturating_add(1), || {
        format!(
            "experience sentinel_level must be max_level + 1 = {}",
            max_level.saturating_add(1)
        )
    });
    StatRulesParts {
        max_level,
        bonus: bonus_tables(&p.stat_bonus, e),
        constants: constants(&p.formulas.formulas, e),
        accuracy_level_add: level_rows(
            "level_additions.accuracy",
            &p.formulas.level_additions.accuracy,
            &p.formulas.level_additions.accuracy_q,
            max_level,
            e,
        ),
        evasion_level_add: level_rows(
            "level_additions.evasion",
            &p.formulas.level_additions.evasion,
            &p.formulas.level_additions.evasion_q,
            max_level,
            e,
        ),
        xp_to_level: xp_rows(&p.experience, e),
        death_loss: loss_rows(&p.penalties, e),
        classes: classes(p, max_level, e),
        starter_weapon: weapon(&p.weapon, e),
    }
}

fn check_provenance(p: &Parsed, e: &mut Errors) {
    e.require(p.stat_bonus.q == Q && p.formulas.q == Q, || format!("q must be {Q}"));
    let dp = &p.stat_bonus.source;
    let mut same = |file: &str, s: &SourceRef| {
        e.require(s.repository == dp.repository && s.revision == dp.revision, || {
            format!(
                "{file}: datapack source {}@{} differs from stat_bonus's",
                s.repository, s.revision
            )
        });
    };
    same("tables/experience.toml", &p.experience.source);
    same("tables/penalties.toml", &p.penalties.source);
    same("tables/starter_weapon.toml", &p.weapon.source);
    for (rel, c) in &p.classes {
        same(rel, &c.source);
    }
    let f = &p.formulas.formulas;
    let literals: [(&str, &[String]); 16] = [
        ("level_mod", &f.level_mod.literal),
        ("p_atk", &f.p_atk.literal),
        ("p_def", &f.p_def.literal),
        ("max_hp", &f.max_hp.literal),
        ("max_mp", &f.max_mp.literal),
        ("accuracy", &f.accuracy.literal),
        ("evasion", &f.evasion.literal),
        ("hit_chance", &f.hit_chance.literal),
        ("crit_rate", &f.crit_rate.literal),
        ("phys_damage", &f.phys_damage.literal),
        ("random_damage", &f.random_damage.literal),
        ("attack_speed", &f.attack_speed.literal),
        ("attack_interval", &f.attack_interval.literal),
        ("damage_hate", &f.damage_hate.literal),
        ("xp_cap", &f.xp_cap.literal),
        ("town_respawn", &f.town_respawn.literal),
    ];
    for (id, lines) in literals {
        e.require(!lines.is_empty() && lines.iter().all(|l| !l.trim().is_empty()), || {
            format!("formulas.{id}: needs at least one non-empty literal source line")
        });
    }
}

fn bonus_tables(f: &StatBonusFile, e: &mut Errors) -> StatBonusTables {
    let expected = usize::try_from(f.max_index.saturating_sub(f.min_index))
        .unwrap_or(usize::MAX)
        .saturating_add(1);
    e.require(f.min_index == 0 && expected == BONUS_TABLE_LEN, || {
        format!("stat_bonus index range {}..={} must be 0..=99", f.min_index, f.max_index)
    });
    let mut table = |name: &str, rows: &BonusRows| {
        e.require(rows.bonus.len() == expected && rows.bonus_q.len() == expected, || {
            format!(
                "stat_bonus.{name}: {} literals / {} scaled rows, expected {expected} (indices {}..={})",
                rows.bonus.len(),
                rows.bonus_q.len(),
                f.min_index,
                f.max_index
            )
        });
        BonusTable::new(
            rows.bonus
                .iter()
                .enumerate()
                .map(|(i, lit)| {
                    e.decimal(&format!("stat_bonus.{name}[{i}]"), lit, rows.bonus_q.get(i).copied())
                })
                .collect(),
        )
    };
    StatBonusTables {
        str: table("str", &f.str),
        dex: table("dex", &f.dex),
        con: table("con", &f.con),
        int: table("int", &f.int),
        wit: table("wit", &f.wit),
        men: table("men", &f.men),
    }
}

fn constants(f: &FormulaSet, e: &mut Errors) -> FormulaConstants {
    let r = &f.town_respawn;
    FormulaConstants {
        level_mod_offset: f.level_mod.offset,
        level_mod_divisor: f.level_mod.divisor,
        accuracy_dex_multiplier: f.accuracy.dex_sqrt_multiplier,
        evasion_dex_multiplier: f.evasion.dex_sqrt_multiplier,
        evasion_cap: f.evasion.cap,
        hit_base: f.hit_chance.base,
        hit_per_point: f.hit_chance.per_point,
        hit_scale: f.hit_chance.scale,
        hit_min_permille: f.hit_chance.min_permille,
        hit_max_permille: f.hit_chance.max_permille,
        hit_roll_range: f.hit_chance.roll_range,
        crit_scale: f.crit_rate.scale,
        crit_cap_permille: f.crit_rate.cap_permille,
        crit_roll_range: f.crit_rate.roll_range,
        damage_coefficient: f.phys_damage.coefficient,
        crit_multiplier: f.phys_damage.crit_multiplier,
        fist_random_base: f.random_damage.fist_base,
        random_divisor: f.random_damage.divisor,
        attack_speed_cap: f.attack_speed.cap,
        attack_interval_ms: f.attack_interval.numerator_ms,
        impact_divisor: f.attack_interval.impact_divisor,
        hate_numerator: f.damage_hate.numerator,
        hate_level_offset: f.damage_hate.level_offset,
        hate_cap: f.damage_hate.cap,
        respawn_restore_hp: e.decimal(
            "town_respawn.restore_hp",
            &r.restore_hp,
            Some(r.restore_hp_q),
        ),
        respawn_restore_mp: e.decimal(
            "town_respawn.restore_mp",
            &r.restore_mp,
            Some(r.restore_mp_q),
        ),
        spawn_protection_seconds: r.spawn_protection_seconds,
    }
}

fn level_rows(
    ctx: &str,
    lits: &[String],
    qs: &[i64],
    max_level: u32,
    e: &mut Errors,
) -> Vec<Scaled> {
    let n = usize::try_from(max_level).unwrap_or(usize::MAX);
    e.require(lits.len() == n && qs.len() == n, || {
        format!(
            "{ctx}: {} literals / {} scaled rows, expected one per level 1..={max_level}",
            lits.len(),
            qs.len()
        )
    });
    lits.iter()
        .enumerate()
        .map(|(i, lit)| {
            e.decimal(&format!("{ctx}[level {}]", i.saturating_add(1)), lit, qs.get(i).copied())
        })
        .collect()
}

fn contiguous(ctx: &str, levels: impl Iterator<Item = u32>, last: u32, e: &mut Errors) {
    let got: Vec<u32> = levels.collect();
    let want: Vec<u32> = (1..=last).collect();
    if got != want {
        let missing: Vec<u32> = want.iter().copied().filter(|l| !got.contains(l)).collect();
        e.push(format!(
            "{ctx}: levels must be exactly 1..={last} in order (missing {missing:?}, got {} rows)",
            got.len()
        ));
    }
}

fn xp_rows(f: &ExperienceFile, e: &mut Errors) -> Vec<u64> {
    contiguous("experience.to_level", f.to_level.iter().map(|r| r.level), f.sentinel_level, e);
    f.to_level.iter().map(|r| r.xp).collect()
}

fn loss_rows(f: &PenaltiesFile, e: &mut Errors) -> Vec<Scaled> {
    contiguous(
        "penalties.death_xp_loss",
        f.death_xp_loss.iter().map(|r| r.level),
        f.max_level,
        e,
    );
    f.death_xp_loss
        .iter()
        .map(|r| {
            let ctx = format!("penalties.death_xp_loss[level {}]", r.level);
            let percent = e.decimal(&ctx, &r.percent, None);
            // percent / 100 must be exact at Q.
            if percent.raw() % 100 == 0 {
                let fraction = Scaled::from_raw(percent.raw() / 100);
                e.require(fraction.raw() == r.fraction_q, || {
                    format!(
                        "{ctx}: percent {} is fraction {} at Q, stored {}",
                        r.percent,
                        fraction.raw(),
                        r.fraction_q
                    )
                });
                fraction
            } else {
                e.push(format!("{ctx}: percent {} / 100 is not exact at Q", r.percent));
                Scaled::ZERO
            }
        })
        .collect()
}

fn weapon(f: &WeaponFile, e: &mut Errors) -> WeaponBlock {
    WeaponBlock {
        id: f.id.clone(),
        p_atk: e.decimal("starter_weapon.p_atk", &f.p_atk, Some(f.p_atk_q)),
        crit_rate: f.crit_rate,
        attack_speed: f.p_atk_spd,
        random_damage: f.random_damage,
        accuracy: e.decimal("starter_weapon.accuracy", &f.accuracy, Some(f.accuracy_q)),
        attack_range_l2: f.attack_range,
    }
}

fn classes(p: &Parsed, max_level: u32, e: &mut Errors) -> Vec<ClassTemplate> {
    let mut out: Vec<ClassTemplate> = p
        .classes
        .iter()
        .map(|(rel, c)| class(rel, c, max_level, e))
        .collect();
    out.sort_by(|a, b| a.id.cmp(&b.id));
    out
}

fn class(rel: &str, c: &ClassFile, max_level: u32, e: &mut Errors) -> ClassTemplate {
    let stem = rel.trim_start_matches("classes/").trim_end_matches(".toml");
    e.require(stem == c.id, || format!("{rel}: id {} does not match the file name", c.id));
    let race = Race::parse(&c.race).unwrap_or_else(|| {
        e.push(format!("{rel}: unknown race {}", c.race));
        Race::Human
    });
    let archetype = match c.archetype.as_str() {
        "fighter" => Archetype::Fighter,
        "mystic" => Archetype::Mystic,
        other => {
            e.push(format!("{rel}: unknown archetype {other}"));
            Archetype::Mystic
        },
    };
    let s = &c.p_def_slots;
    let p_def: u32 = [
        s.chest,
        s.legs,
        s.head,
        s.feet,
        s.gloves,
        s.underwear,
        s.cloak,
    ]
    .iter()
    .fold(0_u32, |acc, v| acc.saturating_add(*v));
    ClassTemplate {
        id: c.id.clone(),
        class_id: c.class_id,
        name: c.name.clone(),
        race,
        archetype,
        base: BaseStats {
            str: c.base_stats.str,
            dex: c.base_stats.dex,
            con: c.base_stats.con,
            int: c.base_stats.int,
            wit: c.base_stats.wit,
            men: c.base_stats.men,
        },
        fist_p_atk: e.decimal(
            &format!("{rel}: combat.p_atk"),
            &c.combat.p_atk,
            Some(c.combat.p_atk_q),
        ),
        fist_crit_rate: c.combat.crit_rate,
        fist_attack_speed: c.combat.p_atk_spd,
        p_def_unarmoured: Scaled::from_int(p_def.into()).unwrap_or(Scaled::ZERO),
        hp: curve(&format!("{rel}: hp"), &c.hp, max_level, e),
        mp: curve(&format!("{rel}: mp"), &c.mp, max_level, e),
    }
}

/// Parses a fitted curve and reconciles it with every literal per-level source row.
fn curve(ctx: &str, f: &CurveFile, max_level: u32, e: &mut Errors) -> Quadratic {
    let q = Quadratic {
        base: e.decimal(&format!("{ctx}.base"), &f.base, Some(f.base_q)),
        per_level: e.decimal(&format!("{ctx}.per_level"), &f.per_level, Some(f.per_level_q)),
        accel: e.decimal(&format!("{ctx}.accel"), &f.accel, Some(f.accel_q)),
    };
    let rows = level_rows(&format!("{ctx}.levels"), &f.levels, &f.levels_q, max_level, e);
    for (level, row) in (1_u32..).zip(&rows) {
        match q.at(level) {
            Ok(v) if v == i128::from(row.raw()) => {},
            Ok(v) => e.push(format!("{ctx}: level {level} source row {row} != quadratic {v}/Q")),
            Err(err) => e.push(format!("{ctx}: level {level}: {err}")),
        }
    }
    q
}

fn hex(bytes: &[u8]) -> String {
    use std::fmt::Write as _;
    bytes
        .iter()
        .fold(String::with_capacity(bytes.len().saturating_mul(2)), |mut s, b| {
            let _ = write!(s, "{b:02x}");
            s
        })
}

#[cfg(test)]
#[path = "rules_data_tests.rs"]
mod tests;
