#!/usr/bin/env python3
"""Generate the Phase 1 stat tables from the pinned L2J High Five source.

Reads two local clones at the pinned revisions (see packages/data/SOURCES.md):

    git clone -b develop https://bitbucket.org/l2jserver/l2j-server-game.git
    git clone -b develop https://bitbucket.org/l2jserver/l2j-server-datapack.git
    (checkout GAME_REVISION / DATAPACK_REVISION below)

and writes packages/data/tables/*.toml and packages/data/classes/*.toml:

    python3 packages/data/scripts/gen_tables.py --game PATH --datapack PATH [--check]

Every decimal is kept as its literal source string next to its exact scaled integer
(Q = 1_000_000). Arithmetic uses `decimal` / `fractions` only; no binary floating point
touches a value that is written out. Formula constants are not typed in here: each one is
parsed out of a literal source line that must exist verbatim in the pinned revision, so a
different revision fails loudly instead of drifting. `--check` regenerates in memory and
exits non-zero if any committed file differs.
"""

from __future__ import annotations

import argparse
import json
import re
import subprocess
import sys
import xml.etree.ElementTree as ET
from decimal import ROUND_HALF_UP, Decimal, localcontext
from fractions import Fraction
from pathlib import Path

GAME_REPOSITORY = "https://bitbucket.org/l2jserver/l2j-server-game"
GAME_REVISION = "abfde0490ac52a2106e884b7242c0276c44cdf76"
DATAPACK_REPOSITORY = "https://bitbucket.org/l2jserver/l2j-server-datapack"
DATAPACK_REVISION = "3ca488dd2bd0bfaca43e378886a3c2e37968153a"

Q = 1_000_000
JAVA = "src/main/java/com/l2jserver/gameserver/"
DATA = "src/main/resources/data/"
CONFIG = "src/main/resources/config/character.properties"
HEADER = (
    "# GENERATED by packages/data/scripts/gen_tables.py from the pinned L2J High Five source\n"
    "# (packages/data/SOURCES.md). Do not edit by hand; regenerate instead.\n"
)

# The nine starting classes of planning/01-stat-formulas.md §2.2, in class-id order.
# (file stem, Nightfall id, display name, Nightfall race, archetype)
STARTER_CLASSES = [
    ("HumanFighter", "human_fighter", "Human Fighter", "human", "fighter"),
    ("HumanMystic", "human_mystic", "Human Mystic", "human", "mystic"),
    ("ElvenFighter", "elven_fighter", "Elven Fighter", "elf", "fighter"),
    ("ElvenMystic", "elven_mystic", "Elven Mystic", "elf", "mystic"),
    ("DarkFighter", "dark_fighter", "Dark Elven Fighter", "dark_elf", "fighter"),
    ("DarkMystic", "dark_mystic", "Dark Elven Mystic", "dark_elf", "mystic"),
    ("OrcFighter", "orc_fighter", "Orc Fighter", "orc", "fighter"),
    ("OrcMystic", "orc_mystic", "Orc Mystic", "orc", "mystic"),
    ("DwarvenFighter", "dwarven_fighter", "Dwarven Fighter", "dwarf", "fighter"),
]
STAT_ORDER = ["STR", "DEX", "CON", "INT", "WIT", "MEN"]
STARTER_WEAPON_ITEM = 2369  # Squire's Sword, equipped by HF fighter starters (initialEquipment.xml)


class SourceError(Exception):
    """The pinned source does not contain what this script expects."""


# ---------------------------------------------------------------------------
# Exact decimal helpers
# ---------------------------------------------------------------------------


def to_q(literal: str) -> int:
    """Exact Q-scaled integer of a decimal literal; fails if it is not exactly representable."""
    if not re.fullmatch(r"-?\d+(\.\d+)?", literal):
        raise SourceError(f"not a plain decimal: {literal!r}")
    scaled = Fraction(literal) * Q
    if scaled.denominator != 1:
        raise SourceError(f"{literal} is not exact at Q={Q}")
    return int(scaled)


def fraction_literal(value: Fraction) -> str:
    """Plain decimal string of a fraction whose denominator divides a power of ten."""
    for digits in range(0, 13):
        scaled = value * 10**digits
        if scaled.denominator == 1:
            return str(Decimal(int(scaled)).scaleb(-digits)) if digits else str(int(scaled))
    raise SourceError(f"{value} has no finite decimal form")


def round_half_up(value: Decimal, exponent: str) -> Decimal:
    return value.quantize(Decimal(exponent), rounding=ROUND_HALF_UP)


def closed_form(base: str, offset: Fraction, x: int, precision: int) -> Decimal:
    """base^(x + offset) evaluated in decimal at `precision` significant digits."""
    with localcontext() as ctx:
        ctx.prec = precision
        exponent = Decimal(offset.numerator) / Decimal(offset.denominator) + x
        return (exponent * Decimal(base).ln()).exp()


def closed_form_two_decimals(base: str, offset: Fraction, x: int) -> Decimal:
    """Round base^(x+offset) half-up to 0.01, doubling precision until two runs agree."""
    precision = 40
    previous = round_half_up(closed_form(base, offset, x, precision), "0.01")
    while True:
        precision *= 2
        current = round_half_up(closed_form(base, offset, x, precision), "0.01")
        if current == previous:
            return current
        if precision > 2000:
            raise SourceError(f"{base}^({x}{offset:+}) does not converge")
        previous = current


# ---------------------------------------------------------------------------
# Source access
# ---------------------------------------------------------------------------


class Repo:
    def __init__(self, root: Path, revision: str, label: str) -> None:
        head = subprocess.run(
            ["git", "-C", str(root), "rev-parse", "HEAD"],
            check=True,
            capture_output=True,
            text=True,
        ).stdout.strip()
        if head != revision:
            raise SourceError(f"{label} clone is at {head}, expected pinned {revision}")
        self.root = root

    def text(self, rel: str) -> str:
        return (self.root / rel).read_text(encoding="utf-8")

    def line(self, rel: str, literal: str) -> str:
        """Return `literal` if a line of `rel` equals it after stripping whitespace."""
        if literal not in (ln.strip() for ln in self.text(rel).splitlines()):
            raise SourceError(f"{rel}: expected literal line not found: {literal}")
        return literal


def property_value(game: Repo, key: str) -> str:
    match = re.search(rf"^{key}\s*=\s*(\S+)\s*$", game.text(CONFIG), re.M)
    if not match:
        raise SourceError(f"{CONFIG}: {key} not set")
    return match.group(1)


def int_from(pattern: str, literal: str) -> int:
    match = re.search(pattern, literal)
    if not match:
        raise SourceError(f"pattern {pattern!r} not in {literal!r}")
    return int(match.group(1))


# ---------------------------------------------------------------------------
# TOML emission (hand-rolled so output is byte-stable)
# ---------------------------------------------------------------------------


def toml_str(s: str) -> str:
    return json.dumps(s, ensure_ascii=False)


def toml_array(items: list[str], per_line: int = 10, indent: str = "    ") -> str:
    lines = [", ".join(items[i : i + per_line]) for i in range(0, len(items), per_line)]
    return "[\n" + "".join(f"{indent}{ln},\n" for ln in lines) + "]"


def source_block(file: str, repo: str, revision: str, symbol: str | None = None) -> str:
    """Provenance as one inline table, so it cannot capture the keys that follow it."""
    fields = [f"repository = {toml_str(repo)}", f"revision = {toml_str(revision)}", f"file = {toml_str(file)}"]
    if symbol:
        fields.append(f"symbol = {toml_str(symbol)}")
    return "source = { " + ", ".join(fields) + " }\n"


# ---------------------------------------------------------------------------
# Tables
# ---------------------------------------------------------------------------


def gen_stat_bonus(dp: Repo) -> str:
    rel = DATA + "stats/statBonus.xml"
    src = dp.text(rel)
    comments = dict(re.findall(r"<(\w+)>\s*<!--\s*([^>]*?)\s*-->", src))
    root = ET.fromstring(src)
    out = HEADER
    out += (
        "#\n# HF base-stat bonus multipliers. L2J reads these 2-decimal table values at runtime\n"
        "# (BaseStats.java, array index = stat value, MAX_STAT_VALUE = 100, so indices 0..=99);\n"
        "# the generating expression is the source XML comment and is kept for provenance only.\n"
        "# `bonus` is the literal source value, `bonus_q` its exact Q-scaled integer.\n\n"
    )
    out += source_block(rel, DATAPACK_REPOSITORY, DATAPACK_REVISION, "BaseStats.java static loader")
    out += "q = 1000000\nmin_index = 0\nmax_index = 99\n"
    for stat in STAT_ORDER:
        node = root.find(stat)
        if node is None:
            raise SourceError(f"{rel}: no <{stat}>")
        rows = {int(s.get("value")): s.get("bonus") for s in node}
        if sorted(rows) != list(range(100)):
            raise SourceError(f"{rel}: {stat} does not cover 0..=99")
        expression = comments[stat]
        m = re.fullmatch(r"([\d.]+)\^\((\w+)([+-])([\d.]+)\)", expression)
        if not m or m.group(2) != stat:
            raise SourceError(f"{rel}: unexpected expression {expression!r}")
        offset = Fraction(m.group(4)) * (1 if m.group(3) == "+" else -1)
        errata = []
        for idx in range(100):
            fit = closed_form_two_decimals(m.group(1), offset, idx)
            if fit != Decimal(rows[idx]):
                errata.append(f"index {idx}: table {rows[idx]}, expression rounds to {fit}")
        literals = [rows[i] for i in range(100)]
        out += f"\n[{stat.lower()}]\nexpression = {toml_str(expression)}\n"
        if errata:
            out += "# Errata (table is authoritative; expression rounded half-up to 0.01 differs):\n"
            out += "".join(f"#   {e}\n" for e in errata)
        out += "bonus = " + toml_array([toml_str(v) for v in literals]) + "\n"
        out += "bonus_q = " + toml_array([str(to_q(v)) for v in literals]) + "\n"
    return out


def gen_experience(dp: Repo, max_level: int) -> str:
    rel = DATA + "stats/expData.json"
    table = {int(k): int(v) for k, v in json.loads(dp.text(rel)).items()}
    sentinel = max_level + 1
    if any(level not in table for level in range(1, sentinel + 1)):
        raise SourceError(f"{rel}: missing a level in 1..={sentinel}")
    out = HEADER
    out += (
        "#\n# HF cumulative XP required to reach each level (ExperienceData.getExpForLevel).\n"
        f"# MaxPlayerLevel = {max_level} (character.properties). Level {sentinel} is the sentinel:\n"
        f"# PlayableStat.addExp caps XP at xp({sentinel}) - 1, and calculateDeathExpPenalty uses\n"
        f"# xp({sentinel}) - xp({max_level}) as the level-{max_level} span. It is not attainable.\n"
        f"# Source rows above {sentinel} ({', '.join(str(k) for k in sorted(table) if k > sentinel)})"
        " are not used.\n\n"
    )
    out += source_block(rel, DATAPACK_REPOSITORY, DATAPACK_REVISION, "ExperienceData")
    out += f"max_level = {max_level}\nsentinel_level = {sentinel}\n"
    rows = [f"    {{ level = {lv}, xp = {table[lv]} }},\n" for lv in range(1, sentinel + 1)]
    out += "to_level = [\n" + "".join(rows) + "]\n"
    return out


def gen_penalties(dp: Repo, game: Repo, max_level: int) -> str:
    rel = DATA + "stats/chars/playerXpPercentLost.xml"
    root = ET.fromstring(dp.text(rel))
    rows = {int(n.get("level")): n.get("val") for n in root}
    if any(level not in rows for level in range(1, max_level + 1)):
        raise SourceError(f"{rel}: missing a level in 1..={max_level}")
    loss = game.line(
        JAVA + "model/actor/instance/L2PcInstance.java",
        "lostExp = Math.round(((getStat().getExpForLevel(lvl + 1) - getStat().getExpForLevel(lvl))"
        " * percentLost) / 100);",
    )
    out = HEADER
    out += (
        "#\n# HF death XP loss: percent of the current level's XP span\n"
        "# (L2PcInstance.calculateDeathExpPenalty). `percent` is the literal source value,\n"
        "# `fraction_q` = percent / 100 as an exact Q-scaled integer.\n"
        f"# Source literal: {loss}\n"
        "# Nightfall matches Math.round with exact rational arithmetic (plan §3.1); see SOURCES.md errata E-7.\n\n"
    )
    out += source_block(rel, DATAPACK_REPOSITORY, DATAPACK_REVISION, "PlayerXpPercentLostData")
    out += f"max_level = {max_level}\n"
    lines = []
    for lv in range(1, max_level + 1):
        frac = to_q(rows[lv]) // 100
        if to_q(rows[lv]) % 100:
            raise SourceError(f"{rel}: level {lv} percent {rows[lv]} not exact at Q")
        lines.append(
            f"    {{ level = {lv}, percent = {toml_str(rows[lv])}, fraction_q = {frac} }},\n"
        )
    out += "death_xp_loss = [\n" + "".join(lines) + "]\n"
    return out


def gen_formulas(game: Repo, max_level: int) -> str:
    char = JAVA + "model/actor/L2Character.java"
    formulas = JAVA + "model/stats/Formulas.java"
    funcs = JAVA + "model/stats/functions/formulas/"
    stat = JAVA + "model/actor/stat/"

    entries: list[tuple[str, str, str, list[str], list[tuple[str, str]]]] = []

    def formula(fid: str, rel: str, symbol: str, lines: list[str], consts: list[tuple[str, str]]):
        for ln in lines:
            game.line(rel, ln)
        entries.append((fid, rel, symbol, lines, consts))

    lm = "return ((getLevel() + 89) / 100d);"
    formula(
        "level_mod",
        char,
        "L2Character.getLevelMod",
        [lm],
        [
            ("offset", str(int_from(r"getLevel\(\) \+ (\d+)", lm))),
            ("divisor", str(int_from(r"/ (\d+)d", lm))),
        ],
    )
    formula(
        "p_atk",
        funcs + "FuncPAtkMod.java",
        "FuncPAtkMod.calc",
        ["return initVal * BaseStats.STR.calcBonus(effector) * effector.getLevelMod();"],
        [],
    )
    formula(
        "p_def",
        funcs + "FuncPDefMod.java",
        "FuncPDefMod.calc",
        ["return value * effector.getLevelMod();"],
        [],
    )
    formula(
        "max_hp",
        funcs + "FuncMaxHpMul.java",
        "FuncMaxHpMul.calc",
        ["return initVal * BaseStats.CON.calcBonus(effector);"],
        [],
    )
    formula(
        "max_mp",
        funcs + "FuncMaxMpMul.java",
        "FuncMaxMpMul.calc",
        ["return initVal * BaseStats.MEN.calcBonus(effector);"],
        [],
    )
    acc = "double value = initVal + (Math.sqrt(effector.getDEX()) * 6) + level;"
    formula(
        "accuracy",
        funcs + "FuncAtkAccuracy.java",
        "FuncAtkAccuracy.calc",
        [acc, "if (level > 77) {", "value += level - 76;", "if (level > 69) {", "value += level - 69;"],
        [("dex_sqrt_multiplier", str(int_from(r"\* (\d+)\)", acc)))],
    )
    eva = "value += (Math.sqrt(effector.getDEX()) * 6) + level;"
    max_eva = int(property_value(game, "MaxEvasion"))
    formula(
        "evasion",
        funcs + "FuncAtkEvasion.java",
        "FuncAtkEvasion.calc (player branch); CharStat.getEvasionRate cap MaxEvasion",
        [eva, "double diff = level - 69;", "if (level >= 78) {", "diff *= 1.2;", "if (level >= 70) {", "value += diff;"],
        [("dex_sqrt_multiplier", str(int_from(r"\* (\d+)\)", eva))), ("cap", str(max_eva))],
    )
    hit = "int chance = (80 + (2 * (attacker.getAccuracy() - target.getEvasionRate(attacker)))) * 10;"
    formula(
        "hit_chance",
        formulas,
        "Formulas.calcHitMiss",
        [hit, "chance = Math.max(chance, 200);", "chance = Math.min(chance, 980);", "return chance < Rnd.get(1000);"],
        [
            ("base", str(int_from(r"\((\d+) \+", hit))),
            ("per_point", str(int_from(r"\((\d+) \* \(attacker", hit))),
            ("scale", str(int_from(r"\) \* (\d+);", hit))),
            ("min_permille", "200"),
            ("max_permille", "980"),
            ("roll_range", "1000"),
        ],
    )
    crit = "return initVal * BaseStats.DEX.calcBonus(effector) * 10;"
    max_crit = int(property_value(game, "MaxPCritRate"))
    formula(
        "crit_rate",
        funcs + "FuncAtkCritical.java",
        "FuncAtkCritical.calc; CharStat.getCriticalHit cap MaxPCritRate; Formulas.calcCrit",
        [crit],
        [("scale", str(int_from(r"\* (\d+);", crit))), ("cap_permille", str(max_crit)), ("roll_range", "1000")],
    )
    game.line(stat + "CharStat.java", "double val = (int) calcStat(Stats.CRITICAL_RATE, _activeChar.getTemplate().getBaseCritRate(), target, skill);")
    game.line(formulas, "return (target.getStat().calcStat(Stats.DEFENCE_CRITICAL_RATE, rate, null, null) + target.getStat().calcStat(Stats.DEFENCE_CRITICAL_RATE_ADD, 0, null, null)) > Rnd.get(1000);")
    normal = "damage = (76 * damage * proximityBonus) / defence;"
    crit_dmg = (
        "damage = 2 * attacker.calcStat(Stats.CRITICAL_DAMAGE, 1, target, null) * "
        "attacker.calcStat(Stats.CRITICAL_DAMAGE_POS, 1, target, null) * "
        "target.calcStat(Stats.DEFENCE_CRITICAL_DAMAGE, 1, target, null) * "
        "((76 * damage * proximityBonus) / defence);"
    )
    formula(
        "phys_damage",
        formulas,
        "Formulas.calcPhysDam (normal attack)",
        [normal, crit_dmg, "return Math.max(damage, 1);"],
        [
            ("coefficient", str(int_from(r"\((\d+) \* damage", normal))),
            ("crit_multiplier", str(int_from(r"damage = (\d+) \*", crit_dmg))),
        ],
    )
    rnd = "return (1 + ((double) Rnd.get(0 - random, random) / 100));"
    fist = "random = 5 + (int) Math.sqrt(getLevel());"
    formula(
        "random_damage",
        char,
        "L2Character.getRandomDamageMultiplier",
        [fist, rnd],
        [("fist_base", str(int_from(r"= (\d+) \+", fist))), ("divisor", str(int_from(r"/ (\d+)\)\);", rnd)))],
    )
    spd = "return initVal * BaseStats.DEX.calcBonus(effector);"
    formula(
        "attack_speed",
        funcs + "FuncPAtkSpeed.java",
        "FuncPAtkSpeed.calc; PcStat.getPAtkSpd cap MaxPAtkSpeed",
        [spd],
        [("cap", property_value(game, "MaxPAtkSpeed"))],
    )
    interval = "return (int) (500000 / getPAtkSpd());"
    to_hit = "final int timeToHit = timeAtk / 2;"
    formula(
        "attack_interval",
        char,
        "L2Character.calculateTimeBetweenAttacks; L2Character.doAttack",
        [interval, to_hit],
        [("numerator_ms", str(int_from(r"\((\d+) /", interval))), ("impact_divisor", str(int_from(r"/ (\d+);", to_hit)))],
    )
    hate = "addDamageHate(attacker, damage, (damage * 100) / (getLevel() + 7));"
    cap = "_hate = Math.min(_hate + value, 999999999);"
    formula(
        "damage_hate",
        JAVA + "model/actor/L2Attackable.java",
        "L2Attackable.reduceCurrentHp; AggroInfo.addHate",
        [hate],
        [
            ("numerator", str(int_from(r"\(damage \* (\d+)\)", hate))),
            ("level_offset", str(int_from(r"getLevel\(\) \+ (\d+)", hate))),
            ("cap", str(int_from(r"value, (\d+)\)", cap))),
        ],
    )
    game.line(JAVA + "model/AggroInfo.java", cap)
    formula(
        "xp_cap",
        stat + "PlayableStat.java",
        "PlayableStat.addExp; PcStat.getMaxExpLevel",
        ["value = (getExpForLevel(getMaxExpLevel()) - 1 - currentExp);"],
        [("max_level", str(max_level))],
    )
    restore_hp = property_value(game, "RespawnRestoreHP")
    restore_mp = property_value(game, "RespawnRestoreMP")
    protection = property_value(game, "PlayerSpawnProtection")
    formula(
        "town_respawn",
        char,
        "L2Character.doRevive; character.properties RespawnRestoreHP/MP, PlayerSpawnProtection (seconds)",
        ["_status.setCurrentHp(getMaxHp() * character().getRespawnRestoreHP());"],
        [
            ("restore_hp", toml_str(restore_hp)),
            ("restore_hp_q", str(to_q(restore_hp))),
            ("restore_mp", toml_str(restore_mp)),
            ("restore_mp_q", str(to_q(restore_mp))),
            ("spawn_protection_seconds", protection),
        ],
    )

    out = HEADER
    out += (
        "#\n# Formula provenance and constants. Each [formulas.<id>] lists literal lines that exist\n"
        "# verbatim in the pinned revision; every constant below is parsed out of those lines or\n"
        "# out of config/character.properties, never typed in. The Rust evaluator in\n"
        "# apps/api/src/domain/zone implements exactly these ids (plan §3.1).\n\n"
        f"source = {{ repository = {toml_str(GAME_REPOSITORY)}, revision = {toml_str(GAME_REVISION)}, "
        f"config = {toml_str(CONFIG)} }}\n"
        f"q = 1000000\nmax_level = {max_level}\n"
    )
    for fid, rel, symbol, lines, consts in entries:
        out += f"\n[formulas.{fid}]\nfile = {toml_str(rel)}\nsymbol = {toml_str(symbol)}\n"
        out += "literal = [\n" + "".join(f"    {toml_str(ln)},\n" for ln in lines) + "]\n"
        out += "".join(f"{k} = {v}\n" for k, v in consts)

    # Per-level additions, generated from the literal accuracy/evasion branches above.
    acc_add, eva_add = [], []
    for level in range(1, max_level + 1):
        a = Fraction(0)
        if level > 77:
            a += level - 76
        if level > 69:
            a += level - 69
        e = Fraction(0)
        if level >= 70:
            e = Fraction(level - 69) * (Fraction(6, 5) if level >= 78 else 1)
        acc_add.append(fraction_literal(a))
        eva_add.append(fraction_literal(e))
    out += (
        "\n# Level additions on top of `level` (index = level - 1), exact, from the branches above.\n"
        "[level_additions]\n"
        "accuracy = " + toml_array([toml_str(v) for v in acc_add]) + "\n"
        "accuracy_q = " + toml_array([str(to_q(v)) for v in acc_add]) + "\n"
        "evasion = " + toml_array([toml_str(v) for v in eva_add]) + "\n"
        "evasion_q = " + toml_array([str(to_q(v)) for v in eva_add]) + "\n"
    )
    return out


def gen_weapon(dp: Repo) -> str:
    rel = DATA + "stats/items/02300-02399.xml"
    root = ET.fromstring(dp.text(rel))
    item = next((i for i in root if i.get("id") == str(STARTER_WEAPON_ITEM)), None)
    if item is None:
        raise SourceError(f"{rel}: item {STARTER_WEAPON_ITEM} missing")
    sets = {s.get("name"): s.get("val") for s in item.findall("set")}
    funcs = {s.get("stat"): s.get("val") for s in item.find("for").findall("set")}
    if set(funcs) != {"pAtk", "mAtk", "critRate", "pAtkSpd"}:
        raise SourceError(f"{rel}: unexpected funcs {sorted(funcs)}")
    out = HEADER
    out += (
        "#\n# The one fixed starter weapon (plan D1): Squire's Sword, equipped by the HF fighter\n"
        "# starters in initialEquipment.xml. Its stats are L2J <set> funcs (order 0), so they\n"
        "# REPLACE the class fist values (P.Atk, crit base, attack speed) before STR/DEX/level\n"
        "# multipliers apply; they do not add to them. No accuracy func: weapon accuracy is 0.\n\n"
    )
    out += source_block(rel, DATAPACK_REPOSITORY, DATAPACK_REVISION, f"item {STARTER_WEAPON_ITEM}")
    out += (
        f'id = "squires_sword"\nitem_id = {STARTER_WEAPON_ITEM}\nname = {toml_str(item.get("name"))}\n'
        f'weapon_type = {toml_str(sets["weapon_type"])}\n'
        f'p_atk = {toml_str(funcs["pAtk"])}\np_atk_q = {to_q(funcs["pAtk"])}\n'
        f'crit_rate = {int(funcs["critRate"])}\np_atk_spd = {int(funcs["pAtkSpd"])}\n'
        f'random_damage = {int(sets["random_damage"])}\n'
        '# L2 world units, literal; converting to milli-tiles is the combat story\'s job.\n'
        f'attack_range = {int(sets["attack_range"])}\naccuracy = "0"\naccuracy_q = 0\n'
    )
    return out


def gen_class(dp: Repo, stem: str, cid: str, name: str, race: str, archetype: str, max_level: int) -> str:
    rel = DATA + f"stats/chars/baseStats/{stem}.xml"
    root = ET.fromstring(dp.text(rel))
    static = root.find("staticData")

    def num(path: str) -> str:
        node = static.find(path)
        if node is None or node.text is None:
            raise SourceError(f"{rel}: missing {path}")
        return node.text.strip()

    slots = ["chest", "legs", "head", "feet", "gloves", "underwear", "cloak"]
    pdef = {s: int(num(f"basePDef/{s}")) for s in slots}
    levels = {int(lv.get("val")): lv for lv in root.find("lvlUpgainData")}
    if sorted(levels) != list(range(1, max_level + 1)):
        raise SourceError(f"{rel}: lvlUpgainData does not cover 1..={max_level}")

    def curve(key: str) -> str:
        literals = [levels[lv].find(key).text.strip() for lv in range(1, max_level + 1)]
        v = [Fraction(x) for x in literals]
        accel = (v[2] - 2 * v[1] + v[0]) / 2
        per_level = v[1] - v[0] - accel
        base = v[0]
        for i, value in enumerate(v):
            if base + per_level * i + accel * i * i != value:
                raise SourceError(f"{rel}: {key} level {i + 1} is not on the fitted quadratic")
        body = f"\n[{key}]\n"
        body += "# value(L) = base + per_level*(L-1) + accel*(L-1)^2, fitted exactly to every row.\n"
        for label, val in (("base", base), ("per_level", per_level), ("accel", accel)):
            lit = fraction_literal(val)
            body += f"{label} = {toml_str(lit)}\n{label}_q = {to_q(lit)}\n"
        body += "# Literal lvlUpgainData rows, index = level - 1.\n"
        body += "levels = " + toml_array([toml_str(x) for x in literals], per_line=8) + "\n"
        body += "levels_q = " + toml_array([str(to_q(x)) for x in literals], per_line=8) + "\n"
        return body

    out = HEADER
    out += "\n" + source_block(rel, DATAPACK_REPOSITORY, DATAPACK_REVISION, "PlayerTemplateData")
    out += (
        f"id = {toml_str(cid)}\nclass_id = {int(root.find('classId').text)}\nname = {toml_str(name)}\n"
        f"race = {toml_str(race)}\narchetype = {toml_str(archetype)}\n"
        "\n[base_stats]\n"
        + "".join(f"{s.lower()} = {int(num('base' + s))}\n" for s in STAT_ORDER)
        + "\n[combat]\n"
        "# Fist values; the starter weapon's <set> funcs replace p_atk, crit_rate and p_atk_spd.\n"
        f"p_atk = {toml_str(num('basePAtk'))}\np_atk_q = {to_q(num('basePAtk'))}\n"
        f"crit_rate = {int(num('baseCritRate'))}\np_atk_spd = {int(num('basePAtkSpd'))}\n"
        f"attack_range = {int(num('baseAtkRange'))}\n"
        f"run_speed = {int(num('baseMoveSpd/run'))}\nwalk_speed = {int(num('baseMoveSpd/walk'))}\n"
        "\n# Unarmoured P.Def = sum of the per-slot bases (PlayerTemplateData); a worn slot\n"
        "# subtracts its base (FuncPDefMod). Phase 1 has no armour slots occupied.\n"
        "[p_def_slots]\n" + "".join(f"{s} = {pdef[s]}\n" for s in slots)
    )
    out += curve("hp") + curve("mp")
    return out


def generate(game: Repo, dp: Repo) -> dict[str, str]:
    max_level = int(property_value(game, "MaxPlayerLevel"))
    files: dict[str, str] = {}
    files["tables/stat_bonus.toml"] = gen_stat_bonus(dp)
    formulas = gen_formulas(game, max_level)
    files["tables/formulas.toml"] = formulas
    files["tables/experience.toml"] = gen_experience(dp, max_level)
    files["tables/penalties.toml"] = gen_penalties(dp, game, max_level)
    files["tables/starter_weapon.toml"] = gen_weapon(dp)
    for stem, cid, name, race, archetype in STARTER_CLASSES:
        files[f"classes/{cid}.toml"] = gen_class(dp, stem, cid, name, race, archetype, max_level)
    return files


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--game", type=Path, required=True, help="l2j-server-game clone")
    parser.add_argument("--datapack", type=Path, required=True, help="l2j-server-datapack clone")
    parser.add_argument("--out", type=Path, default=Path(__file__).resolve().parent.parent)
    parser.add_argument("--check", action="store_true", help="fail if committed files differ")
    args = parser.parse_args()
    try:
        files = generate(
            Repo(args.game, GAME_REVISION, "game"),
            Repo(args.datapack, DATAPACK_REVISION, "datapack"),
        )
    except SourceError as err:
        print(f"gen_tables: {err}", file=sys.stderr)
        return 2
    stale = []
    for rel, content in sorted(files.items()):
        path = args.out / rel
        if args.check:
            if not path.exists() or path.read_text(encoding="utf-8") != content:
                stale.append(rel)
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8")
    if stale:
        print("gen_tables: stale generated files: " + ", ".join(stale), file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
