#!/usr/bin/env python3
"""Generate Phase 2 race and class catalogs from the pinned L2J High Five datapack.

Reads the local L2J datapack clone at the pinned revision:
    commit 3ca488dd2bd0bfaca43e378886a3c2e37968153a

Generates:
    packages/data/races/*.toml       (5 playable classic races)
    packages/data/professions/*.toml (all 89 classic classes across tiers 0..=3)
    packages/data/growth/*.csv       (per-class HP/MP/CP curves for levels 1..=85)

Usage:
    python3 packages/data/scripts/gen_classes.py --datapack PATH [--check]
"""

from __future__ import annotations

import argparse
import json
import re
import subprocess
import sys
import xml.etree.ElementTree as ET
from decimal import Decimal
from fractions import Fraction
from pathlib import Path

DATAPACK_REPOSITORY = "https://bitbucket.org/l2jserver/l2j-server-datapack"
DATAPACK_REVISION = "3ca488dd2bd0bfaca43e378886a3c2e37968153a"

Q = 1_000_000
DATA_STATS_CHARS = "src/main/resources/data/stats/chars/"
HEADER = (
    "# GENERATED by packages/data/scripts/gen_classes.py from the pinned L2J High Five source\n"
    "# (packages/data/SOURCES.md). Do not edit by hand; regenerate instead.\n\n"
)

# 89 classic class IDs: 0..=57 and 88..=118.
CLASSIC_IDS = set(range(0, 58)) | set(range(88, 119))

# Existing base keys and curated display names for the nine starters.
BASE_KEYS = {
    0: "human_fighter",
    10: "human_mystic",
    18: "elven_fighter",
    25: "elven_mystic",
    31: "dark_fighter",
    38: "dark_mystic",
    44: "orc_fighter",
    49: "orc_mystic",
    53: "dwarven_fighter",
}

# Curated Nightfall labels; l2_ref always retains the unmodified source identity.
NIGHTFALL_DISPLAY_NAMES = {0: 'Human Armsbearer', 1: 'Steel Initiate', 2: 'Twinblade Champion', 3: 'Pike Marshal', 4: 'Oathbound Guard', 5: 'Dawnshield', 6: 'Gravewarden', 7: 'Roadrunner', 8: 'Vault Seeker', 9: 'Farshot', 10: 'Human Spellbearer', 11: 'Ember Initiate', 12: 'Flameweaver', 13: 'Boneweaver', 14: 'Pactkeeper', 15: 'Light Initiate', 16: 'Lifewarden', 17: 'Fatekeeper', 18: 'Elven Armsbearer', 19: 'Groveguard', 20: 'Sanctum Shield', 21: 'Anthem Keeper', 22: 'Wildscout', 23: 'Meadowstalker', 24: 'Starshot', 25: 'Elven Spellbearer', 26: 'Brook Initiate', 27: 'Frostweaver', 28: 'Tidekeeper', 29: 'Grove Seer', 30: 'Lifespring', 31: 'Dark Armsbearer', 32: 'Gloamguard', 33: 'Duskshield', 34: 'Edge Cantor', 35: 'Shade Initiate', 36: 'Riftstalker', 37: 'Nightshot', 38: 'Dark Spellbearer', 39: 'Gloam Initiate', 40: 'Galeweaver', 41: 'Veilkeeper', 42: 'Dusk Seer', 43: 'Soulmender', 44: 'Orc Armsbearer', 45: 'War Initiate', 46: 'Ragebreaker', 47: 'Fist Initiate', 48: 'Stormfist', 49: 'Orc Spiritbearer', 50: 'Flame Seer', 51: 'Clan Sovereign', 52: 'War Cantor', 53: 'Dwarven Armsbearer', 54: 'Delve Initiate', 55: 'Relic Seeker', 56: 'Forge Initiate', 57: 'Siege Crafter', 88: 'Blade Paragon', 89: 'Pike Sovereign', 90: 'Sunshield Paragon', 91: 'Grave Sentinel', 92: 'Horizon Archer', 93: 'Vault Paragon', 94: 'Inferno Sage', 95: 'Soul Harvester', 96: 'Pact Sovereign', 97: 'Dawn Luminary', 98: 'Fate Luminary', 99: 'Sanctum Sentinel', 100: 'Anthem Paragon', 101: 'Gale Stalker', 102: 'Starfall Archer', 103: 'Frost Sage', 104: 'Tide Sovereign', 105: 'Grove Luminary', 106: 'Dusk Sentinel', 107: 'Edge Paragon', 108: 'Rift Hunter', 109: 'Nightfall Archer', 110: 'Tempest Sage', 111: 'Veil Sovereign', 112: 'Soul Luminary', 113: 'Rage Paragon', 114: 'Storm Paragon', 115: 'Clan Paragon', 116: 'War Luminary', 117: 'Relic Paragon', 118: 'Forge Sovereign'}


BASE_RACES = {
    0: "human",
    10: "human",
    18: "elf",
    25: "elf",
    31: "dark_elf",
    38: "dark_elf",
    44: "orc",
    49: "orc",
    53: "dwarf",
}

BASE_ARCHETYPES = {
    0: "fighter",
    10: "mystic",
    18: "fighter",
    25: "mystic",
    31: "fighter",
    38: "mystic",
    44: "fighter",
    49: "mystic",
    53: "fighter",
}

BASE_FIGHTER_XML = {
    "human": "HumanFighter.xml",
    "elf": "ElvenFighter.xml",
    "dark_elf": "DarkFighter.xml",
    "orc": "OrcFighter.xml",
    "dwarf": "DwarvenFighter.xml",
}

RACE_METADATA = {
    "human": {
        "display_name": "Human",
        "l2_ref": "Human",
        "starting_zone": "test_zone",
        "reference_starting_zone": "talking_island_village",
        "start_points": [[0, 0]],
        "mystic_path": True,
        "base_class_ids": [0, 10],
        "passive_skill_keys": ["racial.adaptable"],
    },
    "elf": {
        "display_name": "Elf",
        "l2_ref": "Elf",
        "starting_zone": "test_zone",
        "reference_starting_zone": "elven_village",
        "start_points": [[0, 0]],
        "mystic_path": True,
        "base_class_ids": [18, 25],
        "passive_skill_keys": ["racial.forest_step", "racial.mother_tree_attunement"],
    },
    "dark_elf": {
        "display_name": "Dark Elf",
        "l2_ref": "Dark Elf",
        "starting_zone": "test_zone",
        "reference_starting_zone": "dark_elf_village",
        "start_points": [[0, 0]],
        "mystic_path": True,
        "base_class_ids": [31, 38],
        "passive_skill_keys": ["racial.shadow_precision"],
    },
    "orc": {
        "display_name": "Orc",
        "l2_ref": "Orc",
        "starting_zone": "test_zone",
        "reference_starting_zone": "orc_village",
        "start_points": [[0, 0]],
        "mystic_path": True,
        "base_class_ids": [44, 49],
        "passive_skill_keys": ["racial.iron_constitution"],
    },
    "dwarf": {
        "display_name": "Dwarf",
        "l2_ref": "Dwarf",
        "starting_zone": "test_zone",
        "reference_starting_zone": "dwarven_village",
        "start_points": [[0, 0]],
        "mystic_path": False,
        "base_class_ids": [53],
        "passive_skill_keys": ["racial.pack_mule", "racial.keen_eye", "racial.artisan_hands"],
    },
}

SUBCLASS_EQUIVALENT_SETS = [
    {5, 6, 20, 33},
    {8, 23, 36},
    {9, 24, 37},
    {12, 27, 40},
    {14, 28, 41},
]

# Explicit errata: retail classList.xml has incorrect parents for 34 and 104.
PARENT_ERRATA = {
    34: 32,   # Bladedancer parent is Palus Knight (32), not Shillien Knight (33)
    104: 28,  # Elemental Master parent is Elemental Summoner (28), not Elven Wizard (26)
}


class SourceError(Exception):
    """The pinned source does not match expectations."""


def to_snake_case(name: str) -> str:
    s = name.replace("'", "").replace("-", " ")
    s = re.sub(r"[^a-zA-Z0-9 ]", "", s)
    s = re.sub(r"\s+", "_", s.strip())
    return s.lower()


def toml_str(s: str) -> str:
    return json.dumps(s, ensure_ascii=False)


def source_block(rel_file: str, repo: str, revision: str, symbol: str) -> str:
    fields = [
        f"repository = {toml_str(repo)}",
        f"revision = {toml_str(revision)}",
        f"file = {toml_str(rel_file)}",
        f"symbol = {toml_str(symbol)}",
    ]
    return "source = { " + ", ".join(fields) + " }\n"


class Datapack:
    def __init__(self, root: Path) -> None:
        try:
            head = subprocess.run(
                ["git", "-C", str(root), "rev-parse", "HEAD"],
                check=True,
                capture_output=True,
                text=True,
            ).stdout.strip()
        except Exception as exc:
            raise SourceError(f"failed to check git revision of {root}: {exc}") from exc

        if head != DATAPACK_REVISION:
            raise SourceError(f"datapack clone is at {head}, expected pinned {DATAPACK_REVISION}")
        self.root = root

    def rel(self, subpath: str) -> str:
        return DATA_STATS_CHARS + subpath

    def read_xml(self, subpath: str) -> ET.Element:
        path = self.root / self.rel(subpath)
        if not path.is_file():
            raise SourceError(f"missing expected datapack file: {path}")
        return ET.parse(path).getroot()


def collect_classes_and_growth(dp: Datapack) -> tuple[dict[int, dict], dict[str, str]]:
    cl_root = dp.read_xml("classList.xml")
    base_dir = dp.root / dp.rel("baseStats")
    if not base_dir.is_dir():
        raise SourceError(f"missing baseStats directory: {base_dir}")

    # Map classId -> (xml_filename, xml_root)
    xml_by_cid: dict[int, tuple[str, ET.Element]] = {}
    for p in sorted(base_dir.glob("*.xml")):
        tree = ET.parse(p)
        cid_el = tree.getroot().find("classId")
        if cid_el is not None and cid_el.text:
            cid = int(cid_el.text.strip())
            xml_by_cid[cid] = (p.name, tree.getroot())

    # Build raw hierarchy from classList.xml
    raw_parents: dict[int, int] = {}
    l2_refs: dict[int, str] = {}
    for c in cl_root.findall("class"):
        cid = int(c.attrib["classId"])
        if cid in CLASSIC_IDS:
            l2_refs[cid] = c.attrib["name"]
            pid = c.attrib.get("parentClassId")
            if pid is not None:
                raw_parents[cid] = int(pid)

    # Apply errata
    parents = dict(raw_parents)
    for cid, fixed_pid in PARENT_ERRATA.items():
        if cid in parents:
            parents[cid] = fixed_pid

    # Validate all 89 IDs exist
    if set(l2_refs.keys()) != CLASSIC_IDS:
        raise SourceError(f"classList.xml missing classic IDs: {CLASSIC_IDS - set(l2_refs.keys())}")

    # Calculate tiers and roots
    tiers: dict[int, int] = {}
    roots: dict[int, int] = {}
    for cid in CLASSIC_IDS:
        curr = cid
        tier = 0
        seen = {curr}
        while curr in parents:
            curr = parents[curr]
            if curr in seen:
                raise SourceError(f"cyclic lineage detected at classId {cid}")
            seen.add(curr)
            tier += 1
        tiers[cid] = tier
        roots[cid] = curr

    tier_counts = {t: sum(1 for cid in CLASSIC_IDS if tiers[cid] == t) for t in range(4)}
    if tier_counts != {0: 9, 1: 18, 2: 31, 3: 31}:
        raise SourceError(f"unexpected tier distribution: {tier_counts}")

    classes: dict[int, dict] = {}
    growth_csvs: dict[str, str] = {}

    for cid in sorted(CLASSIC_IDS):
        if cid not in xml_by_cid:
            raise SourceError(f"missing baseStats XML for classId {cid}")
        xml_fname, xml_root = xml_by_cid[cid]
        rel_file = dp.rel(f"baseStats/{xml_fname}")

        sd = xml_root.find("staticData")
        if sd is None:
            raise SourceError(f"{xml_fname}: missing staticData element")

        stats = {
            "str": int(sd.find("baseSTR").text.strip()),
            "dex": int(sd.find("baseDEX").text.strip()),
            "con": int(sd.find("baseCON").text.strip()),
            "int": int(sd.find("baseINT").text.strip()),
            "wit": int(sd.find("baseWIT").text.strip()),
            "men": int(sd.find("baseMEN").text.strip()),
        }
        stat_sum = sum(stats.values())
        if stat_sum != 170:
            raise SourceError(f"{xml_fname}: base stats sum to {stat_sum}, expected 170")

        root_id = roots[cid]
        if root_id not in BASE_RACES:
            raise SourceError(f"classId {cid} has unknown lineage root {root_id}")

        race = BASE_RACES[root_id]
        archetype = BASE_ARCHETYPES[root_id]
        tier = tiers[cid]
        parent = parents.get(cid)
        min_level = {0: 1, 1: 20, 2: 40, 3: 76}[tier]

        l2_ref = l2_refs[cid]
        key = BASE_KEYS.get(cid, to_snake_case(l2_ref))
        display_name = NIGHTFALL_DISPLAY_NAMES[cid]

        subclass_allowed = (tier == 2 and cid not in (51, 57))
        subclass_equivs: list[int] = []
        for s in SUBCLASS_EQUIVALENT_SETS:
            if cid in s:
                subclass_equivs = sorted(s - {cid})
                break

        # Parse lvlUpgainData exactly
        lvl_nodes = xml_root.findall("lvlUpgainData/level")
        if len(lvl_nodes) != 85:
            raise SourceError(f"{xml_fname}: expected 85 levels in lvlUpgainData, found {len(lvl_nodes)}")

        csv_lines = ["level,hp,mp,cp"]
        prev_hp: Decimal | None = None
        prev_mp: Decimal | None = None
        prev_cp: Decimal | None = None

        for idx, ln in enumerate(lvl_nodes, start=1):
            val_attr = int(ln.attrib["val"])
            if val_attr != idx:
                raise SourceError(f"{xml_fname}: expected level val={idx}, found {val_attr}")

            hp_str = ln.find("hp").text.strip()
            mp_str = ln.find("mp").text.strip()
            cp_str = ln.find("cp").text.strip()

            for stat_name, s in [("hp", hp_str), ("mp", mp_str), ("cp", cp_str)]:
                if not re.fullmatch(r"\d+(\.\d+)?", s):
                    raise SourceError(f"{xml_fname} lvl {idx}: invalid plain decimal {stat_name}={s}")
                frac_len = len(s.split(".")[1]) if "." in s else 0
                if frac_len > 6:
                    raise SourceError(f"{xml_fname} lvl {idx}: {stat_name}={s} exceeds 6 decimals (not exact at Q)")
                d = Decimal(s)
                if d <= 0:
                    raise SourceError(f"{xml_fname} lvl {idx}: {stat_name}={s} is non-positive")

            hp_dec = Decimal(hp_str)
            mp_dec = Decimal(mp_str)
            cp_dec = Decimal(cp_str)

            if prev_hp is not None:
                if hp_dec < prev_hp or mp_dec < prev_mp or cp_dec < prev_cp:
                    raise SourceError(f"{xml_fname} lvl {idx}: resource decreased ({hp_dec} < {prev_hp} etc)")
            prev_hp, prev_mp, prev_cp = hp_dec, mp_dec, cp_dec

            csv_lines.append(f"{idx},{hp_str},{mp_str},{cp_str}")

        growth_csvs[key] = "\n".join(csv_lines) + "\n"

        classes[cid] = {
            "id": cid,
            "key": key,
            "display_name": display_name,
            "l2_ref": l2_ref,
            "race": race,
            "tier": tier,
            "parent": parent,
            "min_level": min_level,
            "archetype": archetype,
            "base_class_id": root_id,
            "subclass_allowed": subclass_allowed,
            "subclass_equivalents": subclass_equivs,
            "growth": key,
            "base_stats": stats,
            "movement": {"walk": int(sd.findtext("baseMoveSpd/walk")), "run": int(sd.findtext("baseMoveSpd/run")), "swim": int(sd.findtext("baseMoveSpd/fastSwim"))},
            "collision": {"radius_male": sd.findtext("collisionMale/radius"), "height_male": sd.findtext("collisionMale/height"), "radius_female": sd.findtext("collisionFemale/radius"), "height_female": sd.findtext("collisionFemale/height")},
            "source_file": rel_file,
        }

    # Verify ancestor stat inheritance and consistency
    for cid, cdata in classes.items():
        if cdata["tier"] > 0:
            pid = cdata["parent"]
            parent_data = classes[pid]
            if parent_data["tier"] + 1 != cdata["tier"]:
                raise SourceError(f"class {cid}: parent tier {parent_data['tier']} != {cdata['tier'] - 1}")
            if parent_data["race"] != cdata["race"]:
                raise SourceError(f"class {cid}: parent race {parent_data['race']} != {cdata['race']}")
            if parent_data["base_class_id"] != cdata["base_class_id"]:
                raise SourceError(f"class {cid}: parent root {parent_data['base_class_id']} != {cdata['base_class_id']}")
            if parent_data["archetype"] != cdata["archetype"]:
                raise SourceError(f"class {cid}: parent archetype {parent_data['archetype']} != {cdata['archetype']}")
            if parent_data["base_stats"] != cdata["base_stats"]:
                raise SourceError(f"class {cid}: base stats mismatch with parent {pid}")

    return classes, growth_csvs


def collect_races(dp: Datapack) -> dict[str, dict]:
    races: dict[str, dict] = {}

    for race_id, meta in RACE_METADATA.items():
        fname = BASE_FIGHTER_XML[race_id]
        rel_file = dp.rel(f"baseStats/{fname}")
        xml_root = dp.read_xml(f"baseStats/{fname}")

        sd = xml_root.find("staticData")
        if sd is None:
            raise SourceError(f"{fname}: missing staticData")

        moves = sd.find("baseMoveSpd")
        walk = int(moves.find("walk").text.strip())
        run = int(moves.find("run").text.strip())
        swim = int(moves.find("slowSwim").text.strip())

        col_m = sd.find("collisionMale")
        col_f = sd.find("collisionFemale")
        radius_male = col_m.find("radius").text.strip()
        height_male = col_m.find("height").text.strip()
        radius_female = col_f.find("radius").text.strip()
        height_female = col_f.find("height").text.strip()

        # Validate collision decimals
        for dim, val in [
            ("radius_male", radius_male),
            ("height_male", height_male),
            ("radius_female", radius_female),
            ("height_female", height_female),
        ]:
            if not re.fullmatch(r"\d+(\.\d+)?", val) or Decimal(val) <= 0:
                raise SourceError(f"{fname}: invalid collision decimal {dim}={val}")

        breath = int(sd.find("baseBreath").text.strip())
        safe_fall = int(sd.find("baseSafeFall").text.strip())

        races[race_id] = {
            "id": race_id,
            "display_name": meta["display_name"],
            "l2_ref": meta["l2_ref"],
            "starting_zone": meta["starting_zone"],
            "reference_starting_zone": meta["reference_starting_zone"],
            "start_points": meta["start_points"],
            "mystic_path": meta["mystic_path"],
            "base_class_ids": meta["base_class_ids"],
            "passive_skill_keys": meta["passive_skill_keys"],
            "movement": {
                "walk": walk,
                "run": run,
                "swim": swim,
            },
            "collision": {
                "radius_male": radius_male,
                "radius_female": radius_female,
                "height_male": height_male,
                "height_female": height_female,
            },
            "traits": {
                "breath": breath,
                "safe_fall": safe_fall,
            },
            "source_file": rel_file,
        }

    return races


def format_profession_toml(c: dict) -> str:
    out = HEADER
    out += source_block(c["source_file"], DATAPACK_REPOSITORY, DATAPACK_REVISION, "PlayerTemplateData")
    out += f"id = {c['id']}\n"
    out += f"key = {toml_str(c['key'])}\n"
    out += f"display_name = {toml_str(c['display_name'])}\n"
    out += f"l2_ref = {toml_str(c['l2_ref'])}\n"
    out += f"race = {toml_str(c['race'])}\n"
    out += f"tier = {c['tier']}\n"
    if c["parent"] is not None:
        out += f"parent = {c['parent']}\n"
    out += f"min_level = {c['min_level']}\n"
    out += f"archetype = {toml_str(c['archetype'])}\n"
    out += f"base_class_id = {c['base_class_id']}\n"
    out += f"subclass_allowed = {'true' if c['subclass_allowed'] else 'false'}\n"
    equiv_str = "[" + ", ".join(str(x) for x in c["subclass_equivalents"]) + "]"
    out += f"subclass_equivalents = {equiv_str}\n"
    out += f"growth = {toml_str(c['growth'])}\n\n"

    out += "[movement]\n"
    for key, value in c["movement"].items():
        out += f"{key} = {value}\n"
    out += "\n# Collision source dimensions at Q=1,000,000 world units.\n[collision]\n"
    for key, value in c["collision"].items():
        scaled = Fraction(value) * Q
        if scaled.denominator != 1:
            raise SourceError(f"collision {value} is not exact at Q")
        out += f"{key} = {int(scaled)}\n"
    out += "\n"
    bs = c["base_stats"]
    out += (
        "[base_stats]\n"
        f"str = {bs['str']}\n"
        f"dex = {bs['dex']}\n"
        f"con = {bs['con']}\n"
        f"int = {bs['int']}\n"
        f"wit = {bs['wit']}\n"
        f"men = {bs['men']}\n\n"
    )

    out += "[transfer]\n"
    if c["tier"] == 0:
        out += "requires = []\n"
    else:
        out += f'requires = [{{ item = "class_transfer_token_{c["tier"]}", count = 1 }}]\n'
    out += "quest_hooks = []\n"

    return out


def format_race_toml(r: dict) -> str:
    out = HEADER
    out += source_block(r["source_file"], DATAPACK_REPOSITORY, DATAPACK_REVISION, "PlayerTemplateData")
    out += f"id = {toml_str(r['id'])}\n"
    out += f"display_name = {toml_str(r['display_name'])}\n"
    out += f"l2_ref = {toml_str(r['l2_ref'])}\n"
    out += f"starting_zone = {toml_str(r['starting_zone'])}\n"
    out += f"reference_starting_zone = {toml_str(r['reference_starting_zone'])}\n"
    sp_str = "[" + ", ".join(f"[{pt[0]}, {pt[1]}]" for pt in r["start_points"]) + "]"
    out += f"start_points = {sp_str}\n"
    out += f"mystic_path = {'true' if r['mystic_path'] else 'false'}\n"
    bc_str = "[" + ", ".join(str(x) for x in r["base_class_ids"]) + "]"
    out += f"base_class_ids = {bc_str}\n"
    ps_str = "[" + ", ".join(toml_str(k) for k in r["passive_skill_keys"]) + "]"
    out += f"passive_skill_keys = {ps_str}\n\n"

    m = r["movement"]
    out += (
        "[movement]\n"
        f"walk = {m['walk']}\n"
        f"run = {m['run']}\n"
        f"swim = {m['swim']}\n\n"
    )

    c = r["collision"]
    out += (
        "[collision]\n"
        f"radius_male = {toml_str(c['radius_male'])}\n"
        f"radius_female = {toml_str(c['radius_female'])}\n"
        f"height_male = {toml_str(c['height_male'])}\n"
        f"height_female = {toml_str(c['height_female'])}\n\n"
    )

    t = r["traits"]
    out += (
        "[traits]\n"
        f"breath = {t['breath']}\n"
        f"safe_fall = {t['safe_fall']}\n"
    )

    return out


def generate_all(dp: Datapack) -> dict[str, str]:
    classes, growth_csvs = collect_classes_and_growth(dp)
    races = collect_races(dp)

    files: dict[str, str] = {}

    for race_id, rdata in sorted(races.items()):
        files[f"races/{race_id}.toml"] = format_race_toml(rdata)

    for cid, cdata in sorted(classes.items()):
        key = cdata["key"]
        files[f"professions/{key}.toml"] = format_profession_toml(cdata)

    for key, csv_content in sorted(growth_csvs.items()):
        files[f"growth/{key}.csv"] = csv_content

    return files


def embedded_inventory(files: dict[str, str]) -> str:
    lines = ["// Generated by gen_classes.py; source values remain in catalog TOML/CSV files.",
             "const EMBEDDED_CLASSES: &[(&str, &str)] = &["]
    for path in sorted(files):
        lines.extend(["    (", f'        "{path}",',
                      f'        include_str!("../../../../packages/data/{path}"),', "    ),"])
    lines.append("];\n")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--datapack", type=Path, required=True, help="l2j-server-datapack clone")
    parser.add_argument("--out", type=Path, default=Path(__file__).resolve().parent.parent)
    parser.add_argument("--check", action="store_true", help="fail if committed files differ")
    args = parser.parse_args()

    try:
        dp = Datapack(args.datapack)
        files = generate_all(dp)
    except SourceError as err:
        print(f"gen_classes: {err}", file=sys.stderr)
        return 2

    stale: list[str] = []
    for rel, content in sorted(files.items()):
        path = args.out / rel
        if args.check:
            if not path.exists() or path.read_text(encoding="utf-8") != content:
                stale.append(rel)
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8")

    inventory = args.out.parent.parent / "apps/api/src/infrastructure/class_data_embedded.rs"
    inventory_text = embedded_inventory(files)
    if args.check:
        if not inventory.exists() or inventory.read_text() != inventory_text:
            stale.append(str(inventory))
    elif inventory.parent.exists():
        inventory.write_text(inventory_text)

    if stale:
        print("gen_classes: stale generated files: " + ", ".join(stale), file=sys.stderr)
        return 1

    return 0


if __name__ == "__main__":
    sys.exit(main())
