//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "characters")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub account_id: Uuid,
    #[sea_orm(column_type = "Text")]
    pub name: String,
    #[sea_orm(column_type = "Text", unique)]
    pub name_normalized: String,
    #[sea_orm(column_type = "Text")]
    pub race: String,
    pub level: i32,
    pub str: i16,
    pub dex: i16,
    pub con: i16,
    pub int: i16,
    pub wit: i16,
    pub men: i16,
    #[sea_orm(column_type = "Float")]
    pub pos_x: f32,
    #[sea_orm(column_type = "Float")]
    pub pos_y: f32,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
