//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "character_transfer_receipts")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub character_id: Uuid,
    #[sea_orm(primary_key, auto_increment = false)]
    pub ordinal: i16,
    #[sea_orm(unique_key = "character_transfer_receipts_account_id_key_key")]
    pub account_id: Uuid,
    #[sea_orm(column_type = "Text")]
    pub operation: String,
    #[sea_orm(unique_key = "character_transfer_receipts_account_id_key_key")]
    pub key: Uuid,
    pub target_class_id: i32,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::characters::Entity",
        from = "Column::CharacterId",
        to = "super::characters::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Characters,
    #[sea_orm(
        belongs_to = "super::idempotency_keys::Entity",
        from = "(Column::AccountId, Column::Operation, Column::Key)",
        to = "(super::idempotency_keys::Column::AccountId, super::idempotency_keys::Column::Operation, super::idempotency_keys::Column::Key)",
        on_update = "NoAction",
        on_delete = "Restrict"
    )]
    IdempotencyKeys,
}

impl Related<super::characters::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Characters.def()
    }
}

impl Related<super::idempotency_keys::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::IdempotencyKeys.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
