//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "character_class_slots")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub character_id: Uuid,
    #[sea_orm(primary_key, auto_increment = false)]
    pub slot: i16,
    pub class_id: i32,
    pub level: i32,
    pub exp: i64,
    pub sp: i64,
    pub is_dual: bool,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::character_certifications::Entity")]
    CharacterCertifications,
    #[sea_orm(has_many = "super::character_learned_skills::Entity")]
    CharacterLearnedSkills,
    #[sea_orm(
        belongs_to = "super::characters::Entity",
        from = "Column::CharacterId",
        to = "super::characters::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Characters,
}

impl Related<super::character_certifications::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CharacterCertifications.def()
    }
}

impl Related<super::character_learned_skills::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CharacterLearnedSkills.def()
    }
}

impl Related<super::characters::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Characters.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
