//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "characters")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub account_id: Uuid,
    #[sea_orm(column_type = "Text")]
    pub name: String,
    #[sea_orm(column_type = "Text", unique)]
    pub name_normalized: String,
    #[sea_orm(column_type = "Text")]
    pub race: String,
    pub level: i32,
    pub str: i16,
    pub dex: i16,
    pub con: i16,
    pub int: i16,
    pub wit: i16,
    pub men: i16,
    #[sea_orm(column_type = "Float")]
    pub pos_x: f32,
    #[sea_orm(column_type = "Float")]
    pub pos_y: f32,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    pub xp: i64,
    pub hp: Option<i32>,
    pub mp: Option<i32>,
    #[sea_orm(column_type = "Text")]
    pub class_profile: String,
    pub alive: bool,
    pub revision: i64,
    pub base_class_id: i32,
    pub current_class_id: i32,
    pub active_class_slot: i16,
    #[sea_orm(column_type = "Text")]
    pub sex: String,
    pub hair_style: i32,
    pub hair_color: i32,
    pub face: i32,
    pub sp: i64,
    pub cp: i32,
    pub token_tier_1_count: i32,
    pub token_tier_2_count: i32,
    pub milestone_claimed_mask: i16,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::character_class_slots::Entity")]
    CharacterClassSlots,
    #[sea_orm(has_many = "super::character_transfer_receipts::Entity")]
    CharacterTransferReceipts,
    #[sea_orm(has_many = "super::play_tickets::Entity")]
    PlayTickets,
}

impl Related<super::character_class_slots::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CharacterClassSlots.def()
    }
}

impl Related<super::character_transfer_receipts::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CharacterTransferReceipts.def()
    }
}

impl Related<super::play_tickets::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PlayTickets.def()
    }
}

impl Related<super::idempotency_keys::Entity> for Entity {
    fn to() -> RelationDef {
        super::character_transfer_receipts::Relation::IdempotencyKeys.def()
    }
    fn via() -> Option<RelationDef> {
        Some(
            super::character_transfer_receipts::Relation::Characters
                .def()
                .rev(),
        )
    }
}

impl ActiveModelBehavior for ActiveModel {}
