//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "character_certifications")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub character_id: Uuid,
    #[sea_orm(primary_key, auto_increment = false)]
    pub subclass_slot: i16,
    #[sea_orm(primary_key, auto_increment = false)]
    pub ordinal: i16,
    #[sea_orm(column_type = "Text")]
    pub skill_key: String,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::character_class_slots::Entity",
        from = "(Column::CharacterId, Column::SubclassSlot)",
        to = "(super::character_class_slots::Column::CharacterId, super::character_class_slots::Column::Slot)",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    CharacterClassSlots,
}

impl Related<super::character_class_slots::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CharacterClassSlots.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
