//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "zone_epochs")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub zone_id: i32,
    #[sea_orm(primary_key, auto_increment = false)]
    pub epoch: i64,
    pub started_at: DateTimeWithTimeZone,
    pub first_seq: Option<i64>,
    pub last_checkpointed_tick: Option<i64>,
    pub last_recorded_tick: Option<i64>,
    pub closed_at: Option<DateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
