//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "zone_snapshots")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub zone_id: i32,
    #[sea_orm(primary_key, auto_increment = false)]
    pub epoch: i64,
    #[sea_orm(column_type = "VarBinary(StringLen::None)")]
    pub snapshot: Vec<u8>,
    pub jetstream_snapshot_seq: i64,
    pub jetstream_first_seq: Option<i64>,
    pub time_origin_ms: i64,
    #[sea_orm(column_type = "Text")]
    pub build_id: String,
    #[sea_orm(column_type = "Text")]
    pub config_hash: String,
    pub schema_version: i32,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
