[/Script/EngineSettings.GameMapsSettings]
GameDefaultMap=/Engine/Maps/Entry.Entry
EditorStartupMap=/Engine/Maps/Entry.Entry
GlobalDefaultGameMode=/Script/Engine.GameModeBase

[/Script/Engine.RendererSettings]
r.DefaultFeature.AutoExposure=False
r.DynamicGlobalIlluminationMethod=1
r.ReflectionMethod=1
r.Shadow.Virtual.Enable=1
r.Nanite.ProjectEnabled=True
r.GenerateMeshDistanceFields=True

[/Script/Engine.Engine]
; No networking driver: this client never hosts or joins a UE session.
!NetDriverDefinitions=ClearArray

[/Script/WindowsTargetPlatform.WindowsTargetSettings]
DefaultGraphicsRHI=DefaultGraphicsRHI_DX12

[/Script/LinuxTargetPlatform.LinuxTargetSettings]
TargetedRHIs=SF_VULKAN_SM6

[/Script/AndroidFileServerEditor.AndroidFileServerRuntimeSettings]
bEnablePlugin=True
bAllowNetworkConnection=True
SecurityToken=01A118FB33237E3CB89482CBB12F84D3
bIncludeInShipping=False
bAllowExternalStartInShipping=False
bCompileAFSProject=False
bUseCompression=False
bLogFiles=False
bReportStats=False
ConnectionType=USBOnly
bUseManualIPAddress=False
ManualIPAddress=

