# Tasks inherited by every project using the node toolchain.
$schema: 'https://moonrepo.dev/schemas/tasks.json'

inheritedBy:
  toolchains: ['node']

fileGroups:
  sources:
    - 'src/**/*'
  configs:
    - '*.{js,json,ts}'
    - 'tsconfig*.json'

tasks:
  typecheck:
    command: 'tsc --noEmit'
    inputs:
      - '@group(sources)'
      - '@group(configs)'
