# Tasks inherited by every project using the rust toolchain.
$schema: 'https://moonrepo.dev/schemas/tasks.json'

inheritedBy:
  toolchains: ['rust']

fileGroups:
  sources:
    - 'src/**/*'
    - 'build.rs'
    - 'Cargo.toml'

tasks:
  build:
    command: 'cargo build'
    inputs:
      - '@group(sources)'
      - '/Cargo.lock'
      - '/Cargo.toml'
  check:
    command: 'cargo check'
    inputs:
      - '@group(sources)'
  lint:
    command: 'cargo clippy -- -D warnings'
    inputs:
      - '@group(sources)'
  format:
    command: 'cargo fmt --check'
    inputs:
      - '@group(sources)'
  test:
    command: 'cargo test'
    inputs:
      - '@group(sources)'
