//! Postgres adapters via `SeaORM` on top of the sqlx pool. See
//! docs/engineering/database-guidelines.md.

mod account_repository;
mod character_repository;
/// Generated by `moon run api:entities`; never hand-edited.
#[allow(missing_docs, unreachable_pub, clippy::pedantic)]
pub mod entities;
mod idempotency;
mod migrations;
mod session_repository;

pub use account_repository::PgAccountRepository;
pub use character_repository::PgCharacterRepository;
pub use migrations::Migrator;
use sea_orm::{DatabaseConnection, SqlxPostgresConnector};
use sea_orm_migration::MigratorTrait;
pub use session_repository::PgSessionRepository;
use sqlx::postgres::PgPoolOptions;
use sqlx::{Connection, PgPool};

/// Wraps the shared sqlx pool in a `SeaORM` connection. Cheap; both views share connections.
#[must_use]
pub fn connection_from_pool(pool: &PgPool) -> DatabaseConnection {
    SqlxPostgresConnector::from_sqlx_postgres_pool(pool.clone())
}

/// Opens a bounded pool and runs pending migrations.
///
/// Pool size: Postgres performs best with few connections; 10 is plenty for one game server
/// process and keeps us far below the default `max_connections = 100`.
pub async fn connect(database_url: &str) -> anyhow::Result<DatabaseConnection> {
    let pool = PgPoolOptions::new()
        .max_connections(10)
        .acquire_timeout(std::time::Duration::from_secs(5))
        .connect(database_url)
        .await?;
    migrate(&pool).await?;
    tracing::info!("postgres connected, migrations applied");
    Ok(connection_from_pool(&pool))
}

/// Arbitrary fixed key for the migration advisory lock ("NIGHTFAL" as ASCII).
const MIGRATION_LOCK_KEY: i64 = 0x4e49_4748_5446_414c;

/// Applies pending migrations while holding a Postgres advisory lock, so instances starting
/// together queue up instead of racing on DDL and `seaql_migrations`; the losers find nothing
/// left to apply. `sea-orm-migration` takes no lock of its own on Postgres.
///
/// The lock is session-scoped and lives on its own connection, which is closed (not returned
/// to the pool) afterwards: that releases the lock even if the unlock statement fails.
pub async fn migrate(pool: &PgPool) -> anyhow::Result<()> {
    let mut lock_conn = pool.acquire().await?;
    sqlx::query("SELECT pg_advisory_lock($1)")
        .bind(MIGRATION_LOCK_KEY)
        .execute(&mut *lock_conn)
        .await?;
    let result = Migrator::up(&connection_from_pool(pool), None).await;
    lock_conn.detach().close().await.ok();
    result?;
    Ok(())
}
