//! Postgres adapters via `SeaORM` on top of the sqlx pool. See
//! docs/engineering/database-guidelines.md.

mod character_repository;
/// Generated by `moon run api:entities`; never hand-edited.
#[allow(missing_docs, unreachable_pub, clippy::pedantic)]
pub mod entities;
mod migrations;

pub use character_repository::PgCharacterRepository;
pub use migrations::Migrator;
use sea_orm::{DatabaseConnection, SqlxPostgresConnector};
use sea_orm_migration::MigratorTrait;
use sqlx::postgres::PgPoolOptions;
use sqlx::PgPool;

/// Wraps the shared sqlx pool in a `SeaORM` connection. Cheap; both views share connections.
#[must_use]
pub fn connection_from_pool(pool: &PgPool) -> DatabaseConnection {
    SqlxPostgresConnector::from_sqlx_postgres_pool(pool.clone())
}

/// Opens a bounded pool and runs pending migrations.
///
/// Pool size: Postgres performs best with few connections; 10 is plenty for one game server
/// process and keeps us far below the default `max_connections = 100`.
pub async fn connect(database_url: &str) -> anyhow::Result<DatabaseConnection> {
    let pool = PgPoolOptions::new()
        .max_connections(10)
        .acquire_timeout(std::time::Duration::from_secs(5))
        .connect(database_url)
        .await?;
    let db = connection_from_pool(&pool);
    Migrator::up(&db, None).await?;
    tracing::info!("postgres connected, migrations applied");
    Ok(db)
}
